BANK_ABBREVIATION = {"AB-BANK": "AB Bank Limited",
                     "AGRANI": "Agrani Bank Limited",
                     "AL FALAH": "Alfalah Bank Limited",
                     "AL-ARAFAH": "Al-Arafah Islami Bank Limited",
                     "BANK ASIA": "Bank Asia Limited",
                     "BASIC": "Basic Bank Limited",
                     "BCBL": "Bangladesh Commerce Bank Limited (BCBL)",
                     "BDBL": "Bangladesh Development Bank Limited",
                     "BKB": "Bangladesh Krishi Bank (BKB)",
                     "BRAC": "BRAC Bank Limited",
                     "Bengal": "Bengal Commercial Bank",
                     "CBBL": "Community Bank Bangladesh Limited (CBBL)",
                     "CITI N.A.": "Citibank N.A. Bangladesh",
                     "COMMERCIAL B.": "Commercial Bank of Ceylon Limited",
                     "DFIs": "Development Finance Institutions (DFIs)",
                     "DHAKA": "Dhaka Bank Limited",
                     "DUTCH-BANGLA": "Dutch-Bangla Bank Limited",
                     "EBL": "Eastern Bank Limited",
                     "EXIM": "Export Import Bank of Bangladesh Limited",
                     "FBs": "Foreign Banks (FBs)",
                     "FIRST SECU": "First Security Islami Bank Limited",
                     "GIBL": "Grameen Bank (GIBL)",
                     "HABIB": "Habib Bank Limited",
                     "HSBC": "HSBC Bangladesh",
                     "ICB": "Investment Corporation of Bangladesh (ICB)",
                     "IFIC": "IFIC Bank Limited",
                     "ISLAMI": "Islami Bank Bangladesh Limited",
                     "JAMUNA": "Jamuna Bank Limited",
                     "JANATA": "Janata Bank Limited",
                     "MDBL": "Mercantile Bank Limited",
                     "MERCANTILE": "Mercantile Bank Limited",
                     "MGBL": "Meghna Bank Limited",
                     "MMBL": "Modhumoti Bank Limited (MMBL)",
                     "MUTUAL TRUST": "Mutual Trust Bank Limited",
                     "NBL": "National Bank Limited (NBL)",
                     "NBP": "National Bank of Pakistan (NBP)",
                     "NCCBL": "National Credit & Commerce Bank Limited (NCCBL)",
                     "NRBBL": "NRB Bank Limited (NRBBL)",
                     "NRBCBL": "NRB Commercial Bank Limited (NRBCBL)",
                     "ONE BANK": "One Bank Limited",
                     "PCBs": "Private Commercial Banks (PCBs)",
                     "PKB": "Probashi Kallyan Bank (PKB)",
                     "PREMIER": "Premier Bank Limited",
                     "PRIME": "Prime Bank Limited",
                     "PUBALI": "Pubali Bank Limited",
                     "Padma": "Padma Bank Limited",
                     "RAKUB": "Rajshahi Krishi Unnayan Bank (RAKUB)",
                     "RUPALI": "Rupali Bank Limited",
                     "SBACBL": "South Bangla Agriculture and Commerce Bank Limited (SBACBL)",
                     "SBI": "State Bank of India (SBI)",
                     "SHAHJALAL": "Shahjalal Islami Bank Limited",
                     "SHIMANTO": "Shimanto Bank Limited",
                     "SIBL": "Social Islami Bank Limited",
                     "SONALI": "Sonali Bank Limited",
                     "SOUTHEAST": "Southeast Bank Limited",
                     "STAN.CHART": "Standard Chartered Bank",
                     "STANDARD": "Standard Bank Limited",
                     "THE CITY": "The City Bank Limited",
                     "TRUST BANK": "Trust Bank Limited",
                     "UCBL": "United Commercial Bank Limited (UCBL)",
                     "UNBL": "Union Bank Limited (UNBL)",
                     "UTTARA": "Uttara Bank Limited",
                     "WOORI": "Woori Bank"}


DEPOSIT_TYPE = {"Savings Deposit": "Savings Deposit",
                "Special Notice Deposit (SND)": "Special Notice Deposit (SND) Deposit",
                "Fixed Deposit": "Fixed Deposit"}

TENURE = {"Savings Deposit": ["Not Applicable"],
          "Special Notice Deposit (SND)": ["< 1.00 crore",
                                           "1.00 crore but <25.00 crore",
                                           "25.00 crore but <50.00 crore",
                                           "50.00 crore but <100.00 crore",
                                           "100.00 crore and above"],
          "Fixed Deposit": ["3 months but<6 months",
                            "6 months but<1 year",
                            "1 year but<2 years",
                            "2 years but<3 years",
                            "3 years and above"]}
